version: '3.9'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db  # Persist MongoDB data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/onix"

volumes: 
  mongodb-data:
